### ISSUE TITLE
Unable to open photos in GIMP or any other external editor

### ISSUE THREAD

**Issue by scx** [flathub/com.rawtherapee.RawTherapee#1]
Error message:
```
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown
```

**Comment by scx** [comment]
This issue was fixed a couple weeks ago.
https://github.com/scx/rawtherapee-flatpak/releases/tag/v5.7+20190926

It seems that someone can't even properly copy my patches but still thinks that he is the right person to maintain this package.
https://github.com/flathub/com.rawtherapee.RawTherapee/commit/4032961eab1dd969472bc67f39325b545d0c63b4

Anyway, PR is on the way.

**Comment by barthalion** [comment]
Do you honestly expect that you will get away with such behavior towards other maintainers? That's an easy way to get stripped of push access to **any** repository. It's the last time you're being warned.

**Comment by barthalion** [comment]
And no, deleting your comment won't change that.
