### ISSUE TITLE
No easy way to update Lensfun database

### ISSUE THREAD

**Issue by gnafuthegreat** [flathub/com.rawtherapee.RawTherapee#18]
Apologies if this should be reported further upstream, but it seems to be a particular issue when running the Flatpak.  I'm also hoping someone might be able to point me to a simpler way.

Essentially, I'm trying to update the Lensfun database as I have in the past because the data included with RawTherapee doesn't include my camera (Panasonic GX85) or one of my favorite lenses (Sigma 24mm Super-Wide II).  I have tried running `lensfun-update-data` and the updated data is available under `~/.local/share/lensfun/`, but the Flatpak version of RawTherapee doesn't seem to see it (presumably due to limitations in what parts of the filesystem it can access).  I can't seem to specify a location in RawTherapee; it seems to only look in a couple locations and that's it.

Where do I need to copy these updated files to get the current lens info in RawTherapee?  Is there anything that can be changed in the Flatpak so it can look in `~/.local/share/lensfun/`?  Should I file an upstream feature request to see RawTherapee incorporate Lensfun database updating into the UI?  (Or maybe that's already being considered; I haven't found it yet.)

Thanks for maintaining this!  I have been enjoying using Fedora Silverblue and I like the Flatpak concept.

**Comment by gnafuthegreat** [comment]
Probably not the "right" or "best" way to do it, but for now I was able to get it working by running this:

`sudo cp .local/share/lensfun/updates/version_1/* /sysroot/ostree/deploy/fedora/var/lib/flatpak/app/com.rawtherapee.RawTherapee/x86_64/stable/148a25a918ff4c4287188c85d822502287f76030e48ece683ba206b646748cd1/files/share/lensfun/version_1/`

I'm not sure if this will persist after a reboot, and I'm sure it will be overwritten the next time there's an update to RawTherapee.  But hey, it works for now!  Not a fix, but I wanted to share so it's out there.

**Comment by hfiguiere** [comment]
this is not the way.

the problem lies in LenFun that is not designed really for that. We can try to have similar solution than for the Darktable flatpak.

ie, it's not simple.

**Comment by OldNick** [comment]
The right way to do it - in the absence of any advice  : 

1 : Install Lensfun - any instance of Lensfun within the flatpak won't work - your distribution likely has a package, if not, installing from source is very straight forward.

2 : update your lensfun database - command line "lensfun-update-data" _without admin privileges._ This will install the update to ~/.local/share/lensfun/updates/version_1

3 : edit the RawTherapee "options" file - go to the last line where it says **"[Lensfun] DBDirectory="** and fill in with the path above. 

4 : close the "options" file and delete any cache files (bleachbit helps here)

Start RT and it should find the files

When you update Lensfun again, be sure to check has updateded to the same folder and, if not, repeat 2, changing the path if necessary, delete cache etc.
