### ISSUE TITLE
Extremely laggy mouse behaviour

### ISSUE THREAD

**Issue by janrinze** [flathub/com.rawtherapee.RawTherapee#28]
Moving the mouse over the RawTherapee window makes it stutter and hang at random places. Sometimes for sever seconds. This is very inconvenient. I'm running Debian (Asahi Linux) on a Mac Studio Ultra. So CPU power is not likely an issue. Other QT5 applications will run very smooth without any lag on the mouse.

This is not Panning. This is simply moving the mouse over the RawTherapee window with no mouse buttons pressed.

**Comment by hfiguiere** [comment]
it's not a Qt app, so "other QT5 applications" is comparing apple with oranges.

**Comment by paperdigits** [comment]
I'd suspect this is something GTK and driver related.

**Comment by hfiguiere** [comment]
Isn't this #27 ?

**Comment by janrinze** [comment]
> Isn't this #27 ?

Yes, seems to be related to wayland. I'll leave this to #27.
