### ISSUE TITLE
Update the Flatpak package in Flathub? (also thinking Steam Deck)

### ISSUE THREAD

**Issue by vrement** [flathub/com.rawtherapee.RawTherapee#29]
It is a bit behind https://flathub.org/apps/com.rawtherapee.RawTherapee

I have never managed to get AppImage package to install or open or anything for that matter for some reason when i try to launch it. Flatpak opens up an easy usage on Steam Deck too!

Could it be updated to be current? Thank you so much in advance in any case.

**Comment by paperdigits** [comment]
It is up to date with the current stable release.

**Comment by hfiguiere** [comment]
![image](https://github.com/flathub/com.rawtherapee.RawTherapee/assets/114441/aa5879a2-cddb-4d19-a9a6-3279add50292)

It will be updated when there is a new release.
